name: LPCPlus
description: A chat formatting plugin for LuckPerms. A fork of LPC
version: 0.1-SNAPSHOT
main: me.wikmor.lpcplus.LPCPlus
author: Emma_TheSigma
api-version: 1.20
softdepend: [PlaceholderAPI, LuckPerms]
website: https://github.com/EmmaTheSigmaDev/LPC-Plus
commands:
  lpcplus:
    description: Reload the configuration of LPCPlus.
    permission: lpcplus.reload
    usage: "Usage: /lpcplus reload"