name: LPCPlus
description: A chat formatting plugin for LuckPerms
version: 0.1-SNAPSHOT
main: me.wikmor.lpcplus.LPCPlus
author: [Emma_TheSigma]
api-version: 1.20
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
website: https://hangar.papermc.io/EmmaTheSigma/LPC-Plus
commands:
  lpcplus:
    description: Reload the configuration of LPCPlus.
    permission: lpcplugin.reload
    usage: "Usage: /lpcplus reload"